version: '3.10.7'
services: 
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:80
    ports:
      - 80:80 
    volumes:
      - .:/app
    depends_on:
      - sqlite3

  sqlite3:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - "./db/:/root/db"
      